#!/bin/sh
#
#    Copyright 2018 NEOautus Ltd. (http://neoautus.com)
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may not
#    use this file except in compliance with the License. You may obtain a copy of
#    the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

SCRIPTDIR="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPT="$(basename "$0")"
SCRIPTPATH="$SCRIPTDIR/$SCRIPT"
OS_TYPE="$(uname -s)"

java=java
if [ -n "$JAVA_HOME" ]; then
	java="$JAVA_HOME/bin/java"
elif [ ! -e "$(which java)" ]; then
    java="$(which java)"
elif [ -e "$SCRIPTDIR/../jdk/bin/java" ]; then
    JAVA_HOME="$( cd "$(dirname "$SCRIPTDIR/../jdk/bin")" ; pwd -P )"
    java="$JAVA_HOME/bin/java"
fi

exec "$java" -jar "$SCRIPTPATH" "$@"
exit 1

